### PR TITLE
Add linux-aarch64 support

### LINKED ISSUE #37: Build package for linux-aarch64
### Comment:

Useful for running on a linux container on a macbook

### PR DESCRIPTION
**Pull request by SaravananSathyanandhaQC**
Fixes #37 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jonmmease** [comment]
Thanks @SaravananSathyanandhaQC, agreed that this is very useful. Will approve if CI is happy.

**Comment by Saravanan21** [comment]
> Thanks @SaravananSathyanandhaQC, agreed that this is very useful. Will approve if CI is happy.

@jonmmease thanks! I just looked again, got closer after fixing some silly mistakes. Just failing one linux-aarch64 build on 73_pypy, something about the wheel not being compatible, need to figure that one out unless you have thoughts

**Comment by SaravananSathyanandhaQC** [comment]
> Thanks @SaravananSathyanandhaQC, agreed that this is very useful. Will approve if CI is happy.

@jonmmease thanks! I just looked again, got closer after fixing some silly mistakes. Just failing one linux-aarch64 build on 73_pypy, something about the wheel not being compatible, need to figure that one out unless you have thoughts

**Comment by jonmmease** [comment]
Awesome, I'll take another look soon. I'm not surprised that the pre-compiled aarch64 wheel isn't compatible with pypy, so I think we'll need to work out how to disable that build.

**Comment by SaravananSathyanandhaQC** [comment]
@conda-forge-admin  please rerender

**Comment by SaravananSathyanandhaQC** [comment]
@jonmmease disabled pypy for aarch64. Do note that conda smithy did a bunch of renaming of files as a result of using `python_impl` as a flag, but no behaviour change

**Comment by jonmmease** [comment]
Thanks for the great work on this @SaravananSathyanandhaQC! Looks great

**Pull request merged**
